# Generated by Django 3.2.9 on 2021-11-17 11:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('slideshow', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Картинка')), ('description', wagtail.core.blocks.RichTextBlock(features=['link'], label='Описание', required=False)), ('publication_date', wagtail.core.blocks.DateBlock(label='Дата', required=False))]), label='Слайды'))], blank=True),
        ),
    ]
