# Generated by Django 3.2.9 on 2021-11-17 12:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('slideshow', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Картинка')), ('description', wagtail.core.blocks.RichTextBlock(features=['link', 'bold'], label='Краткое описание', required=False)), ('full_description', wagtail.core.blocks.RichTextBlock(features=['link'], label='Описание', required=False)), ('publication_date', wagtail.core.blocks.DateBlock(format=['%d.%m.%Y', '%d.%m.%y'], label='Дата', required=False))]), label='Слайды'))], blank=True),
        ),
    ]
