# Generated by Django 3.2.9 on 2021-11-18 07:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'link', 'bold', 'italic'], help_text='Введите название заголовка', label='Заголовок')), ('article', wagtail.core.blocks.StructBlock([('article_text', wagtail.core.blocks.RichTextBlock(label='Текст статьи'))], label='Статья с заголовком'))], blank=True),
        ),
    ]
