# Generated by Django 3.2.9 on 2021-11-18 08:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading_general', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'link', 'bold', 'italic'], help_text='Введите название заголовка', label='Заголовок')), ('article', wagtail.core.blocks.RichTextBlock(label='Статья')), ('article_two_columns', wagtail.core.blocks.RichTextBlock(label='Статья'))], blank=True),
        ),
    ]
