# Generated by Django 3.2.9 on 2021-11-19 09:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('about', '0005_auto_20211119_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChildPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('heading_general', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'link', 'bold', 'italic'], help_text='Введите название заголовка', label='Заголовок')), ('article', wagtail.core.blocks.RichTextBlock(label='Статья')), ('article_two_columns', wagtail.core.blocks.RichTextBlock(label='Статья на двух колонках'))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
